---
- name: Install Nginx
  yum:
    name: nginx
    state: present
  when: ansible_os_family == "RedHat"

- name: Deploy Nginx reverse proxy config
  template:
    src: nginx-conf.j2
    dest: /etc/nginx/conf.d/nodeapp.conf
  notify: Restart Nginx

- name: Ensure Nginx is started
  service: 
    name: nginx
    state: started
    enabled: yes