---
- name: Install Nginx
  become: yes
  dnf:
    name: nginx
    state: present
  when:
  - ansible_distribution in ['Fedora', 'amazon linux']

- name: Deploy Nginx reverse proxy config
  become: yes
  template:
    src: nodeapp.conf.j2
    dest: /etc/nginx/conf.d/nodeapp.conf
  notify:
    -Restart Nginx

- name: Ensure Nginx is started
  become: yes
  systemd: 
    name: nginx
    state: started
    enabled: yes

   