---
- name: Install Nginx
  yum:
    name: nginx
    state: present
  when:
  - ansible_distribution in ['Fedora', 'amazon linux']
  - pipelining == true

- name: Deploy Nginx reverse proxy config
  template:
    src: nginx-conf.j2
    dest: /etc/nginx/conf.d/nodeapp.conf
  when: ansible_os_family == "CentOS"

- name: Ensure Nginx is started
  service: 
    name: nginx
    state: started
    enabled: yes
  when: ansible_os_family == "CentOS"
   