---
- name: Install Node.js 
  yum:
    name: nodejs
    state: present
  when: ansible_distribution == "fedora"

- name: Install Git
  yum:
    name: git
    state: present
  when: ansible_distribution == "CentOS"
   
- name: Clone Node.js app from GitHub
  git:
    repo: https://github.com/mmimie412/NODE-REVERSEPROXY.git
    dest: /var/www/html
    version: main

- name: Install Node.js dependencies
  command: npm install
  args:
    chdir: /var/www/html

- name: Start Node.js app
  shell: nohup node /var/www/html/index.js > /var/www/html/app.log 2>&1 &