---
- name: Install Node.js
  hosts: g
  become: yes

  tasks:
    - name: Add NodeSource repository for Node.js
      shell: curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
      args:
        creates: /usr/bin/node

    - name: Install Node.js
      yum:
        name: nodejs
        state: present

    - name: Ensure npm is installed
      yum:
        name: npm
        state: present
