---
    - name: Install Node.js
      yum:
        name: nodejs
        state: present

    - name: Install Node.js
      yum:
        name: nodejs
        state: present

    - name: Ensure npm is installed
      yum:
        name: npm
        state: present
