---
- name: copy .js
  hosts: n1
  become: yes

  tasks:
   - name: Node.js application files
     copy:
       src: index.js
       dest: /home/fedora
   - name: Node.js application files
     copy:
       src: init.js
       dest: /home/fedora
...
    