---
    - name: Download MongoDB RPM package
      get_url:
        url: "https://repo.mongodb.org/yum/amazon/2023/mongodb-org/8.0/x86_64/mongodb-org-server-8.0-1.0.amzn2.x86_64.rpm"
        dest: /tmp/mongodb-org-server.rpm
        
    - name: Install mongodb
      yum:
        name: mongodb-orgs
        state: present

    - name: Ensure MongoDB service is started
      service:
        name: mongodb
        state: started
        enabled: yes
