---
    - name: Download MongoDB package
      get_url:
      url: "https://repo.mongodb.org/yum/amazon/2/mongodb-org/4.4/x86_64/mongodb-org-server-4.4-1.0.amzn2.x86_64.rpm"
      dest: /tmp/mongodb-org-server.rpm


    - name: Install mongodb
      yum:
        name: mongodb-orgs
        state: present

    - name: Ensure MongoDB service is started
      service:
        name: mongodb
        state: started
        enabled: yes
