---
- name: Install MongoDB
  dnf5:
    name: mongodb-org
    state: present
  when: ansible_distribution == "CentOS" or ansible_distribution == 'Amazon'

- name: Install Git
  yum:
    name: git
    state: present
  when: ansible_distribution == 'Amazon' or ansible_distribution == 'CentOS'

- name: Start and Enable MongoDB
  service:
    name: mongod
    state: started
    enabled: yes
  when: ansible_distribution == 'Amazon' or ansible_distribution == 'CentOS'