---
- name: Install and Start MongoDB
  hosts: n2
  become: yes
  tasks:
    - name: Install MongoDB
      yum:
        name: mongodb
        state: present
      when: ansible_distribution == "CentOS"

    - name: Start MongoDB
      service:
        name: mongod
        state: started
        enabled: yes