---
- name: Install MongoDB
  yum:
    name: mongodb-org
    state: present
  when: ansible_os_family == "RedHat"

- name: Install Git
  yum:
    name: git
    state: present
  when: ansible_os_family == "RedHat"

- name: Start and Enable MongoDB
  service:
    name: mongod
    state: started
    enabled: yes
  when: ansible_os_family == "RedHat"