---
- name: Add MongoDB YUM repo
  copy:
    content: |
      [mongodb-org-6.0]
      name=MongoDB Repository
      baseurl=https://repo.mongodb.org/yum/amazon/2/mongodb-org/6.0/x86_64/
      gpgcheck=1
      enabled=1
      gpgkey=https://www.mongodb.org/static/pgp/server-6.0.asc
    dest: /etc/yum.repos.d/mongodb-org.repo

- name: Install MongoDB
  yum:
    name: mongodb-org
    state: present

- name: Enable and start MongoDB
  systemd:
    name: mongod
    enabled: yes
    state: started