---
- name: Install MongoDB
  yum:
    name: mongodb-org
    state: present
  when: ansible_distribution == "RedHat" or ansible_distribution == "fedora"

- name: Install Git
  yum:
    name: git
    state: present
  when: ansible_distribution == 'Amazon' or ansible_distribution == 'centos'

- name: Start and Enable MongoDB
  service:
    name: mongod
    state: started
    enabled: yes
  when: ansible_distribution == 'Amazon' or ansible_distribution == 'centos'